using CortexPlexus.Core.Abstractions;
using Microsoft.Extensions.Logging;

namespace CortexPlexus.App.Export;

/// <summary>
/// Exports knowledge from CortexPlexus graph into human-readable Markdown files.
/// Generates: architecture-overview.md, api-endpoints.md, dependency-map.md
/// </summary>
public sealed class KnowledgeExporter(
    IGraphStore graphStore,
    IRepositoryStore repoStore,
    ILogger<KnowledgeExporter> logger)
{
    public async Task ExportAsync(string outputPath, CancellationToken ct = default)
    {
        Directory.CreateDirectory(outputPath);

        await ExportArchitectureOverviewAsync(outputPath, ct);
        await SafeExportAsync("API endpoints", () => ExportApiEndpointsAsync(outputPath, ct));
        await SafeExportAsync("data model", () => ExportDependencyMapAsync(outputPath, ct));

        logger.LogInformation("Exported knowledge to {Path}", outputPath);
    }

    private async Task SafeExportAsync(string name, Func<Task> export)
    {
        try { await export(); }
        catch (Exception ex) { logger.LogWarning(ex, "Failed to export {Name} (graph query error, skipping)", name); }
    }

    private async Task<IReadOnlyList<Core.Models.SearchResult>> SafeQueryAsync(
        Func<Task<IReadOnlyList<Core.Models.SearchResult>>> query)
    {
        try { return await query(); }
        catch (Exception ex)
        {
            logger.LogDebug(ex, "Graph query failed, returning empty results");
            return [];
        }
    }

    private async Task ExportArchitectureOverviewAsync(string outputPath, CancellationToken ct)
    {
        var repos = await repoStore.ListAsync(ct);

        // Graph queries may fail if AGE has issues — gracefully degrade
        var diRegs = await SafeQueryAsync(() => graphStore.QueryDiRegistrationsAsync(ct: ct));
        var endpoints = await SafeQueryAsync(() => graphStore.QueryApiEndpointsAsync(ct: ct));
        var entities = await SafeQueryAsync(() => graphStore.QueryEntityMappingsAsync(ct: ct));

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Architecture Overview");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by CortexPlexus. Do not edit manually.");
        sb.AppendLine($"> Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine();

        // Repositories
        sb.AppendLine("## Indexed Repositories");
        sb.AppendLine();
        sb.AppendLine("| Repository | Last Indexed |");
        sb.AppendLine("|------------|-------------|");
        foreach (var repo in repos)
            sb.AppendLine($"| {repo.Name} | {repo.LastIndexed?.ToString("yyyy-MM-dd HH:mm") ?? "never"} |");
        sb.AppendLine();

        // Summary stats
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine($"- **Repositories:** {repos.Count}");
        if (diRegs.Count > 0) sb.AppendLine($"- **DI Registrations:** {diRegs.Count} services");
        if (endpoints.Count > 0) sb.AppendLine($"- **API Endpoints:** {endpoints.Count}");
        if (entities.Count > 0) sb.AppendLine($"- **EF Core Entities:** {entities.Count}");
        sb.AppendLine();

        // DI Registrations
        if (diRegs.Count > 0)
        {
            sb.AppendLine("## DI Container Registrations");
            sb.AppendLine();
            sb.AppendLine("| Service | Implementation | Lifetime |");
            sb.AppendLine("|---------|---------------|----------|");
            foreach (var reg in diRegs)
            {
                // FQN format: "DI:IService->Implementation" or "DI:Service->Service"
                // Name format: "AddScoped<Type>" or "AddSingleton<Type>"
                var fqn = reg.Fqn.StartsWith("DI:") ? reg.Fqn[3..] : reg.Fqn;
                var arrow = fqn.Split("->", 2);
                var service = arrow[0];
                var impl = arrow.Length > 1 ? arrow[1] : "-";
                // Extract lifetime from Name: "AddScoped<...>" → "Scoped"
                var lifetime = reg.Name switch
                {
                    var n when n.StartsWith("AddScoped") => "Scoped",
                    var n when n.StartsWith("AddSingleton") => "Singleton",
                    var n when n.StartsWith("AddTransient") => "Transient",
                    var n when n.StartsWith("AddHostedService") => "Hosted",
                    var n when n.StartsWith("AddHttpClient") => "HttpClient",
                    _ => reg.Name
                };
                // Shorten to just type name (last segment after .)
                var shortService = service.Contains('.') ? service[(service.LastIndexOf('.') + 1)..] : service;
                var shortImpl = impl.Contains('.') ? impl[(impl.LastIndexOf('.') + 1)..] : impl;
                sb.AppendLine($"| `{shortService}` | `{shortImpl}` | {lifetime} |");
            }
            sb.AppendLine();
        }

        var filePath = Path.Combine(outputPath, "architecture-overview.md");
        await File.WriteAllTextAsync(filePath, sb.ToString(), ct);
        logger.LogInformation("Exported architecture overview → {File}", filePath);
    }

    private async Task ExportApiEndpointsAsync(string outputPath, CancellationToken ct)
    {
        var endpoints = await graphStore.QueryApiEndpointsAsync(ct: ct);
        if (endpoints.Count == 0) return;

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# API Endpoints");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by CortexPlexus. Do not edit manually.");
        sb.AppendLine($"> Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine();

        sb.AppendLine("| Method | Route | Handler | File |");
        sb.AppendLine("|--------|-------|---------|------|");
        foreach (var ep in endpoints)
        {
            // FQN format: "API:GET:/route" or "API:POST:/route"
            var fqn = ep.Fqn.StartsWith("API:") ? ep.Fqn[4..] : ep.Fqn;
            var colonIdx = fqn.IndexOf(':');
            var method = colonIdx > 0 ? fqn[..colonIdx] : "?";
            var route = colonIdx > 0 ? fqn[(colonIdx + 1)..] : fqn;
            var file = ep.FilePath is not null ? $"{Path.GetFileName(ep.FilePath)}:{ep.StartLine}" : "-";

            sb.AppendLine($"| `{method}` | `{route}` | `{ep.Name}` | {file} |");
        }
        sb.AppendLine();
        sb.AppendLine($"**Total:** {endpoints.Count} endpoints");

        var filePath = Path.Combine(outputPath, "api-endpoints.md");
        await File.WriteAllTextAsync(filePath, sb.ToString(), ct);
        logger.LogInformation("Exported API endpoints → {File}", filePath);
    }

    private async Task ExportDependencyMapAsync(string outputPath, CancellationToken ct)
    {
        var entities = await graphStore.QueryEntityMappingsAsync(ct: ct);
        if (entities.Count == 0) return;

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Data Model (EF Core)");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by CortexPlexus. Do not edit manually.");
        sb.AppendLine($"> Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine();

        sb.AppendLine("## Entities");
        sb.AppendLine();
        sb.AppendLine("| Entity | Kind | File |");
        sb.AppendLine("|--------|------|------|");
        foreach (var entity in entities)
        {
            var file = entity.FilePath is not null ? $"{Path.GetFileName(entity.FilePath)}:{entity.StartLine}" : "-";
            sb.AppendLine($"| `{entity.Name}` | {entity.Kind} | {file} |");
        }
        sb.AppendLine();
        sb.AppendLine($"**Total:** {entities.Count} entities");

        var filePath = Path.Combine(outputPath, "data-model.md");
        await File.WriteAllTextAsync(filePath, sb.ToString(), ct);
        logger.LogInformation("Exported data model → {File}", filePath);
    }
}
